### ISSUE TITLE
Release checklist for tagging version 1.3.2.3

### ISSUE THREAD

**Issue by benlk** [INN/pym-shortcode#68]
Drawing from Largo's 0.7.0 release checklist issue https://github.com/INN/largo/issues/1798, the SCAMP 0.3 tag checklist https://github.com/INN/doubleclick-for-wp/issues/83, https://github.com/INN/republication-tracker-tool/issues/63, and other issues: 

## Team Prep Work

- [x] copy this issue into this plugin's docs folder with relevant instructions for testing
- [x] check for upstream updates to release.sh in INN/docs into this plugin
- [x] write release announcement
    - [x] GitHub release drafted
        - can be copied from `changelog.md`
        - [ ] includes encouragement to say hi if you're using the plugin. (This fulfills the "who's using our stuff?" goal in https://github.com/INN/largo/issues/1495)
    - [ ] labs.inn.org blog post written and saved as draft, based on changelog
    - [ ] MailChimp campaign for Largo User mailing list drafted: https://github.com/INN/largo/issues/1796
- [x] identify non-Github documentation for this plugin
    - [x] note the location of that documentation
- [x] update outside documentation for this plugin
    - [x] https://support.inn.org/article/100-pym-shortcode -> https://github.com/INN/pym-shortcode/issues/69
    - [ ] any other known doc

## Before merging

The owner of the release needs to complete the following steps **BEFORE** merging the version-bump branch and tagging the release:

- [x] resolve all secret issues, private issues, or issues with the plugin that are otherwise documented outside of this public repository
- [x] resolve all GitHub maintainer security advisories: [merge](https://help.github.com/en/articles/collaborating-in-a-temporary-private-fork-to-resolve-a-security-vulnerability) and [publish](https://help.github.com/en/articles/publishing-a-maintainer-security-advisory).
- [x] update and sort the changelog
    - [x] make sure changelog has all items from this release, and all PRs and issues are linked
    - [x] check that ordering and grouping of items is logical.
    - [x] New features list
    - [x] Dev-facing updates
    - [x] Bugfixes
    - [x] Potentially breaking changes and upgrade notices
    - [x] Which versions of PHP was this tested against? ([why](https://secure.helpscout.net/conversation/963170317/4444/)) List the PHP versions that we're sure of and that WordPress supports. (See https://github.com/INN/largo/issues/1801)
- [x] update description
    - [x] in readme.txt
    - [x] in plugin description comment
- [x] bump version number
    - [x] in readme.txt
    - [x] in pym-shortcode.php
    - [x] in readme.md
    - [x] in docs/maintainer-notes.md
- [x] testing as described in https://github.com/INN/pym-shortcode/blob/master/docs/maintainer-notes.md

## Release process

- [x] bump version number
- [x] tag and push to github
- [x] [release.sh](https://github.com/INN/docs/blob/master/projects/wordpress-plugins/release.sh.md)
- [x] publish release in GitHub -> https://github.com/INN/pym-shortcode/releases/tag/v1.3.2.3
- [x] close milestone

## After release is published

- [ ] update plugins on our sites (inndev? ccs?)
- [ ] publish update announcement blog post
- [ ] tweet announcement and schedule 2-5 for the next 7 days (via TweetDeck, HootSuite, or similar) with simple download prompt or tweets detailing new features, like "Newsroom Staff Pages should be clean and useful. We think so too. See Largo 0.X's new...." Make sure these tweets get cross-tweeted between INN accounts.
- [x] add to Nerd Alert for following week
- [x] create the release ticket for the next milestone from this one -> https://github.com/INN/pym-shortcode/issues/71
- [x] prune stale and merged branches
- [x] notify maintainers of related plugins: News Project, WP AMP

**Comment by benlk** [comment]
Testing without AMP:

Plugin settings:

- [x] Does the plugin settings page work?

Shortcode tests:

- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" pymsrc="https://pym.nprapps.org/pym.v1.min.js"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" pymoptions=" xdomain: '\\*\.npr\.org' "]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" class="one two three four float-left mw_50"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align=""]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align="none"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align="left"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align="center"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align="right"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align="wide"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" align="full"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" id="extremely_specific_id"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" pymsrc="https://pym.nprapps.org/pym.v1.min.js" pymoptions="xdomain: '\\*\.npr\.org'"]`
- [x] `[pym src="https://blog.apps.npr.org/pym.js/examples/table/child.html" pymsrc="https://pym.nprapps.org/pym.v1.min.js" pymoptions=""]`

Gutenberg tests:

- [x] the block, when inserted, prompts users for a URL
- [x] the block's alignment, custom classes, custom ID, and other options are respected.
- [x] the block uses the default pymsrc URL if the pymsrc attribute is not set
- [x] on a site with Gutenberg not installed, the plugin functions
- [x] on a 4.9 site with Gutenberg installed, the plugin functions
- [x] on a 5.0 site, the plugin functions

**Comment by benlk** [comment]
AMP testing was sufficiently covered during #62, so I'm skipping that for this issue.
